ServerEvents.recipes(event => {
    event.remove({output: 'minecraft:netherite_upgrade_smithing_template'})
	event.remove({output: 'minecraft:sentry_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:vex_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:wild_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:coast_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:dune_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:wayfinder_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:raiser_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:shaper_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:host_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:ward_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:silence_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:tide_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:snout_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:rib_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:eye_armor_trim_smithing_template'})
	event.remove({output: 'minecraft:spire_armor_trim_smithing_template'})
	event.remove({output: 'create:mechanical_drill'})
	event.remove({output: 'create:mechanical_saw'})
	event.remove({output: 'create:potato_cannon'})
})